changed: Move locking to environment changed: Refactor some code

diff --git a/share/arno-iptables-firewall/environment b/share/arno-iptables-firewall/environment
--- a/share/arno-iptables-firewall/environment
+++ b/share/arno-iptables-firewall/environment
@@ -1368,7 +1368,7 @@ get_dynamic_host_from_cache()
 # Returns   : Resolved host's IP in "$host_ip"
 get_dynamic_host_cached()
 {
-  # FIXME: Use lock!
+  # FIXME: Use lock or move to plugin!
 
   host_ip=""            # Reset result
   local host="$1"
@@ -1380,7 +1380,7 @@ get_dynamic_host_cached()
     return 0
   fi
 
-  # Check whether we already have it in our (new) cache
+  # Check whether we already have it in our (new) cache. FIXME: Properly handle .new, probably have to move this to a (cron) plugin helper
   host_ip="$(grep "^$host " -m1 "${HOST_CACHE_FILE}.new" |cut -s -f2 -d' ')"
   if [ -n "$host_ip" ]; then
     if [ "$host_ip" = "NO_IP" ]; then
@@ -1458,6 +1458,71 @@ get_dynamic_host_cached()
   fi
 
   return $retval
+}
+
+
+lock_enter()
+{
+  local LOCK_FILE
+
+  if [ -z "$1" ]; then
+    # Global lock
+    LOCK_FILE="/var/lock/aif_global.lock"
+  else
+    LOCK_FILE="/var/lock/aif_$1.lock"
+  fi
+
+  local FAIL_COUNT=0
+
+  while [ $FAIL_COUNT -lt 2 ]; do
+    # We don't want multiple instances so we use a lockfile
+    if ( set -o noclobber; echo "$$" > "$LOCK_FILE") 2> /dev/null; then
+      # Setup int handler
+      trap 'ctrl_handler' INT TERM EXIT
+
+      return 0 # Lock success
+    fi
+
+    # lock failed, check if the process is dead
+    local PID="$(cat "${LOCK_FILE}")"
+
+    # if cat isn't able to read the file, another instance is probably
+    # about to remove the lock -- exit, we're *still* locked
+    # Thanks to Grzegorz Wierzowiecki for pointing out this race condition on
+    # http://wiki.grzegorz.wierzowiecki.pl/code:mutex-in-bash
+    if [ $? -eq 0 ]; then
+      if ! kill -0 "$PID" 2>/dev/null; then
+        # lock is stale, remove it and restart
+        echo "WARNING: Removing stale lock of nonexistant PID ${PID}" >&2
+        rm -f "$LOCK_FILE"
+      fi
+    fi
+
+    FAIL_COUNT=$((FAIL_COUNT + 1))
+  done
+
+  echo "ERROR: Failed to acquire lockfile: $LOCK_FILE. Held by PID $(cat $LOCK_FILE)" >&2
+
+  return 1 # Lock failed
+}
+
+
+lock_leave()
+{
+  local LOCK_FILE
+
+  if [ -z "$1" ]; then
+    # Global lock
+    LOCK_FILE="/var/lock/aif_global.lock"
+  else
+    LOCK_FILE="/var/lock/aif_$1.lock"
+  fi
+
+  # Remove lockfile
+  rm -f "$LOCK_FILE"
+
+  # Disable int handler
+  trap - INT TERM EXIT
 }
 
 
