changed: Refactor dynamic host handling

diff --git a/share/arno-iptables-firewall/plugins/parasitic-net-helper b/share/arno-iptables-firewall/plugins/parasitic-net-helper
--- a/share/arno-iptables-firewall/plugins/parasitic-net-helper
+++ b/share/arno-iptables-firewall/plugins/parasitic-net-helper
@@ -2,14 +2,14 @@
 
 # The plugin configuration file
 ###############################
-PLUGIN_CONF_FILE="traffic-accounting.conf"
+PLUGIN_CONF_FILE="parasitic-net.conf"
 
 # Location of the main configuration file for the firewall
 ##########################################################
 CONFIG_FILE=/etc/arno-iptables-firewall/firewall.conf
 
 # Use a lock file for protection
-LOCK_FILE="/var/lock/aif_traffic_accounting_helper.lock"
+LOCK_FILE="/var/lock/aif_parasitic_net.lock"
 
 # Check if the main config file exists and if so load it
 ########################################################
@@ -86,6 +86,56 @@ sanity_check()
 }
 
 
+# Parse/get hostname. Try to use host cache if applicable
+# Resolve hostname to an IP and store in our (new) cache
+# Arguments : $1 = hostname to resolve
+# Returns   : Resolved host's IP in "$host_ip"
+traffic_accounting_get_host()
+{
+  host_ip=""      # Reset result
+  local host="$1"
+  local retval=0
+
+  printf "${INDENT}Resolving \"$host\" -> "
+
+  if is_numeric_ip "$host"; then
+    echo "$host"
+    host_ip="$host"
+    return 0
+  fi
+
+  # First try to get host from host-cache
+  if [ "$TRAFFIC_ACCOUNTING_USE_HOST_CACHE" != "0" ]; then
+    host_ip=`get_host_from_cache "$host"`
+    local retval=$?
+
+    # TODO: Detect NO-IP condition
+    if [ $retval -eq 0 -o $retval -eq 2 ]; then
+      if [ -n "$host_ip" ]; then
+        echo "$host_ip (cached)"
+      else
+        echo "NO-IP (cached)"
+      fi
+      return 0
+    fi
+  fi
+
+  # Perform normal lookup
+  DNS_FAST_FAIL_ONCE="$DNS_FAST_FAIL"
+  host_ip=`gethostbyname "$host"`
+  retval=$?
+
+  if [ -z "$host_ip" -o $retval -ne 0 ]; then
+    printf "\033[40m\033[1;31mFAILED!\n\033[0m"
+    echo "** ERROR($retval): Unresolvable host \"$host\"! **" >&2
+  else
+    echo "$host_ip"
+  fi
+
+  return $retval
+}
+
+
 traffic_accounting_setup_rules()
 {
   # Touch the log file (just in case it doesn't exist yet):
@@ -128,9 +178,7 @@ traffic_accounting_setup_rules()
     fi
 
     # Get host_ip, if it fails, skip rule
-    # Parse/get hostname. Try to use host cache if applicable
-    # NOTE: get_dynamic_host_cached returns hostname in $host_ip
-    if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
+    if ! traffic_accounting_get_host "$host"; then
       echo "** WARNING: Skipping rule for \"$host\"! **" >&2
       continue
     fi
